name: melos_test
packages:
  - packages/**

command:
  bootstrap:
    hooks:
      post: melos run build_runner

scripts:
  build_runner:
    exec: flutter pub run build_runner build --delete-conflicting-outputs
    packageFilters:
      dependsOn: 'build_runner'
    description: "build_runner"
  analyze:
    exec: flutter analyze
  release:
    exec: flutter build apk
    packageFilters:
      ignore: "app_common"
  fastlane_script:
    run: |
      cd packages/app_1
      fastlane hoge