name: melos_test
packages:
  - packages/**

scripts:
  postbootstrap: melos run build_runner
  build_runner:
    exec: flutter pub run build_runner build --delete-conflicting-outputs
    select-package:
      depends-on: "build_runner"
    description: "build_runner"
  analyze:
    exec: flutter analyze
  release:
    exec: flutter build apk
    select-package:
      ignore: "app_common"
  fastlane_script:
    run: |
      cd packages/app_1
      fastlane hoge